### ISSUE TITLE
just advise

### ISSUE THREAD

**Issue by baoyachi** [beautifulSoup/CNotification#1]
要是加上详细的README.md讲解，配上gif就完美了

**Comment by beautifulSoup** [comment]
@baoyachi  额，这个只是用来配合  [http://sixwolf.net/blog/2016/04/18/Android%E8%87%AA%E5%AE%9A%E4%B9%89Notification%E5%B9%B6%E6%B2%A1%E6%9C%89%E9%82%A3%E4%B9%88%E7%AE%80%E5%8D%95/](http://sixwolf.net/blog/2016/04/18/Android%E8%87%AA%E5%AE%9A%E4%B9%89Notification%E5%B9%B6%E6%B2%A1%E6%9C%89%E9%82%A3%E4%B9%88%E7%AE%80%E5%8D%95/)这篇博客说明如何自定义notification 的，所以就没写文档。
