### ISSUE TITLE
自定义Notification样式问题

### ISSUE THREAD

**Issue by titanseason** [beautifulSoup/CNotification#2]
您好，有2个问题（部分操作系统，例如乐视手机 android 6.0）
1. 默认样式是有左边距的，自定义样式没有左边距
2. 默认样式的标题是白色的，自定义样式的标题颜色是黑色的

由于github无法上传图片，我把图片保存到：http://pan.baidu.com/s/1o8uBTJ8

**Comment by beautifulSoup** [comment]
自定义Notification确实会有很多问题，因为Android碎片化太严重，如果为了简单起见，就给一个固定的颜色值，不然就得根据手机型号进行适配。我们现在的做法是后台建一张表，客户端上传手机型号操作系统等，如果表中收录了该款手机信息，则根据返回的参数自定义View，否则就设置一个默认的背景色，默认的边框。

**Comment by jp1017** [comment]
> 由于github无法上传图片

??什么意思, 直接把图片托进issue就可以啊,怎么无法上传??? @titanseason 



> 我们现在的做法是后台建一张表

求表 :smile: @beautifulSoup

**Comment by beautifulSoup** [comment]
那是上一家公司的故事，已经离职了，我也拿不到了。。。
